// <auto-generated />
using System;
using ControleDeHoras;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeHoras.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250110152109_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ControleDeHoras.Models.Registro", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cliente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataDeInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeModificacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("HoraDeInicio")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("HoraDeTermino")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("HorasUtilizadas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticket")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
